CC = gcc
CFLAGS = -Werror -Wall

gcc -Werror -Wfatal-errors -pedantic-errors -Wall ./src/main.c ./bin/lise.o ./bin/lise/grid.o ../bin/lise/iprostats.o ./bin/lise/iprostats/stats.o ./bin/lise/protiens.o ./bin/lise/protiens/ilig.o ./bin/lise/protiens/ipro.o ./bin/lise/protiens/ilig/atom.o ./bin/lise/protiens/ipro/atom.o


gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise.c -o ./bin/lise.o

gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/grid.c -o ./bin/lise/grid.o

gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/iprostats.c -o ./bin/lise/iprostats.o
gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/iprostats/stats.c -o ./bin/lise/iprostats/stats.o

gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/protiens.c -o ./bin/lise/protiens.o

gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/protiens/ilig.c -o ./bin/lise/protiens/ilig.o
gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/protiens/ipro.c -o ./bin/lise/protiens/ipro.o

gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/protiens/ilig/atom.c -o ./bin/lise/protiens/ilig/atom.o
gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall ./src/lise/protiens/ipro/atom.c -o ./bin/lise/protiens/ipro/atom.o
